# Generated by Django 4.0.4 on 2022-06-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lang_book',
            field=models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
