# Generated by Django 4.0.4 on 2022-06-02 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_lang_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='NO_Pages',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'WORD'), ('other', 'other')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='datetime_uploaded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
