# Generated by Django 4.0.4 on 2022-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_no_pages_book_book_type_book_datetime_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1, max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
