# Generated by Django 4.0.4 on 2022-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(max_length=5000)),
                ('vision', models.TextField(max_length=50000)),
                ('story', models.TextField(max_length=50000)),
                ('work', models.TextField(verbose_name=5000)),
            ],
        ),
    ]
