# Generated by Django 4.0.2 on 2022-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='work',
            field=models.TextField(max_length=5000),
        ),
    ]
